apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccination-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vaccination
  template:
    metadata:
      labels:
        app: vaccination
    spec:
      containers:
        - name: vaccination-app
          image: vaccination-app:latest
          ports:
            - containerPort: 8080